### ISSUE TITLE
Arena client building

### ISSUE THREAD

**Issue by brandonphelps** [siggame/webserver#105]
When the arena adds clients to the database it sets the name of each team to the ['team']['slug'] field of each dictionary block. When the arena runs the tournament it either gets or creates a bye client, which has the name "bye". 

So I am wondering what the outputs of the ['team']['slug'] fields are and if it is possible for them to equal "bye".

**Comment by michaelwisely** [comment]
The team name _could_ be /bye/i, but we've fixed that. Now django-competition validates team names so that [no team can be named "bye" ](https://github.com/michaelwisely/django-competition/blob/develop/src/competition/validators.py#L20).
