### ISSUE TITLE
OpenID options list isn't centered

### ISSUE THREAD

**Issue by michaelwisely** [siggame/webserver#12]
The [login](http://megaminerai.com/accounts/login/) page looks strange. Maybe a side effect of row-fluid?

**Comment by michaelwisely** [comment]
@scj7t4, does the row within the content need to be row-fluid, too? I haven't used the fluid layout stuff before.

**Comment by scj7t4** [comment]
Ugh! I don't know how that didn't get commited. I'll submit a pull request shortly.

**Comment by michaelwisely** [comment]
All fixed by pull request!
