### ISSUE TITLE
Make a new default competition image

### ISSUE THREAD

**Issue by michaelwisely** [siggame/webserver#127]
That PNG is really jagged around the edges and has a white border. We need to export the SVG to clean that stuff up. Or just use the SVG. I don't know which one's better.

**Comment by jonsimington** [comment]
IMO we should use the svg

—

**Comment by michaelwisely** [comment]
Sounds like you're volunteering to fix it @jonsimington! :D SVG's might not work, but it's worth looking into. When a new competition image is added, `django-competition` will [resize it to create a thumbnail](https://github.com/michaelwisely/django-competition/blob/develop/src/competition/models/competition_model.py#L157).

**Comment by jonsimington** [comment]
WE NEED TO DO THIS

**Comment by jonsimington** [comment]
we did it  see https://github.com/michaelwisely/django-competition/commit/9d35a15f31be167f9c8ffb2bc70f59b01c128c13
