### ISSUE TITLE
Use read-only GitHub OAuth scope

### ISSUE THREAD

**Issue by mcatanzaro** [siggame/webserver#129]
I visited megaminerai.com, then clicked GitHub under Sign in with OAuth 2.0. The site requested read/write access to my GitHub account, as well read access to a GitHub organization I belong to. That's too aggressive; surely you should only need read access to my email and maybe basic profile information?

![screenshot from 2015-03-27 16 47 16](https://cloud.githubusercontent.com/assets/1424966/6877714/9029d60e-d4a1-11e4-941b-8faeac4f0e06.png)

**Comment by michaelwisely** [comment]
Thanks for catching this. Fixed in 5799c1c48cb4dad328736b0e49d709ff8261d5f2 and deployed.
