### ISSUE TITLE
Add visualize button to played games list

### ISSUE THREAD

**Issue by mnuck** [siggame/webserver#137]
As a user, I want to rapidly view my completed games from the played games list. Currently this is a 4 click workflow, per game:
1. Click on game row. 
2. Click on Visualize. Tab opens, watch game play out. 
3. Click to close tab.
4. Click back button.

By adding a visualize button to the played games list, this can be reduced to a 2 click workflow, per game:
1. Click on visualize button. Tab opens, watch game play out.
2. Click to close tab.

![image](https://cloud.githubusercontent.com/assets/307658/13474814/b5e45722-e08d-11e5-8d83-a5980ff77809.png)

**Comment by jonsimington** [comment]
I agree, I can get this done tomorrow.

**Comment by jonsimington** [comment]
See https://github.com/siggame/webserver/commit/30d9da9a8d473b3ecd09d7c362f8a2668e00340a
