### ISSUE TITLE
<title>My Profile</title> on other people's profiles

### ISSUE THREAD

**Issue by mnuck** [siggame/webserver#138]
Window title says My Profile on other people's profile. Should say something else if it's not actually my profile.
![screen shot 2016-03-19 at 10 57 27 am](https://cloud.githubusercontent.com/assets/307658/13899310/6917e79c-edc1-11e5-8fd5-972ab2522de6.png)

**Comment by jonsimington** [comment]
Got it, should be an easy fix.  We'll talk about it this week at the web meeting.

**Comment by jonsimington** [comment]
Fixed: https://github.com/siggame/webserver/commit/245a9313bb5910c98130eba0effb6253857bc542
