### ISSUE TITLE
Clarify team creation errors

### ISSUE THREAD

**Issue by cherez** [siggame/webserver#18]
Entering an invalid team name in team creation gives: "This is not an acceptable name."

Could we clarify this with why it's unacceptable, or at least defining what makes an acceptable name?

**Comment by scj7t4** [comment]
I'm looking into this and the current validation regex doesn't make a lot of sense to me. The regex right now is effectively:

``` python
(^\w*[a-zA-Z0-9]+[\w\-\.: ]+$)
```

0 or more underscores then
1 or more Alphanumerics then
1 or more Alphanumerics, underscores, colons, dashes, periods, or spaces

New validator should probably be

``` python
(^[a-zA-Z0-9]+[\w\-\.: \']+$)
```

1 or more alphanumerics
1 or more alphanumerics, colors, dashes, periods, spaces or single quotes.

I really want single quotes in the team name.

**Comment by scj7t4** [comment]
Actually, it may cause glog issues to have the single quotes so let's table that.

**Comment by michaelwisely** [comment]
Added helpful comments in commit michaelwisely/django-competition@8dfadf9c556a76460c563f589ca9219b0946d0a0. I'll deploy this on the webserver later today, probably.
