### ISSUE TITLE
Identify ACM members

### ISSUE THREAD

**Issue by michaelwisely** [siggame/webserver#32]
Since we've been providing discounts to S&T ACM members, it would be lovely to have a way to store ACM membership information on the site. That way, it's easier to see how much a team owes when they pay their registration fee. This shuls help to speed up the process.

**Comment by JustinKellogg** [comment]
Do you know if our main acm site keeps track of members?  If so, could read from theirs.
...I'll email Jacob Magdazziarz
.......dat last name.

**Comment by michaelwisely** [comment]
I haven't been convinced that there's a good way to do this. Regardless how we set things up, we'll have to cross-reference ACM's attendance sheet. I think the coupon thing we've been doing works well.
