### ISSUE TITLE
"Eligible to win prizes" inaccurate

### ISSUE THREAD

**Issue by rorosaurus** [siggame/webserver#37]
My team (http://megaminerai.com/competition/megaminerai-12-mars/team/rorosaurus/) shows up as eligible to win prizes, despite me marking myself as not a full time student during registration.

**Comment by michaelwisely** [comment]
Answers to questions in the registration survey are not connected to team prize eligibility in any way. Eligibility must be marked manually. 

I've got a solution in mind, which will be implemented eventually.

**Comment by rorosaurus** [comment]
Gotcha.  Just wanted to make sure I wasn't missing something.  I assume you have DB access to mark me/my team as ineligible?

**Comment by michaelwisely** [comment]
I do. I also opened a feature request (issue #38) to get that fixed. It is pretty confusing. Thanks for pointing that out @rorosaurus!
