### ISSUE TITLE
Update to Bootstrap 3

### ISSUE THREAD

**Issue by michaelwisely** [siggame/webserver#43]
Somehow the people at Twitter have managed to make Bootstrap even prettier. It's time to upgrade to Bootstrap v3. Also, let's use a CDN this time instead of keeping the style in the repository.

**Comment by jonsimington** [comment]
I started working on this.  Bootstrap 3 is pretty!

**Comment by michaelwisely** [comment]
That's awesome! Be sure to commit your changes to a new branch (other than develop) when you're ready. That should make it easier to merge when it's are ready.

**Comment by michaelwisely** [comment]
I just checked out your bs3updates branch, and it's looking really nice!
