### ISSUE TITLE
Allow sane tag names

### ISSUE THREAD

**Issue by mcatanzaro** [siggame/webserver#55]
At the last competition it wasn't possible to give a tag a sane version number. My team ended up writing out numbers in English: one, two, .... I'm just passing through but that appears to still be an issue:

https://github.com/siggame/webserver/blob/develop/webserver/codemanagement/validators.py

The issue is that a digit cannot be the first or last character. [A-Za-z|\d][\w-.]+[A-Za-z|\d] will probably work.

**Comment by michaelwisely** [comment]
I totally forgot about this. Whoopsie! I'll update the validator this week.
