### ISSUE TITLE
Sharpen Game Result Coloring

### ISSUE THREAD

**Issue by brianwgoldman** [siggame/webserver#63]
I don't know if other people have this issue, but on my display the difference between the "win" highlighting and the "loss" highlighting is very subtle.  After 12 hours of competition, it would be nice for these to really stand out.

Also if possible, could we tint rows that have been viewed?

**Comment by michaelwisely** [comment]
Adding a [bootstrap label](http://getbootstrap.com/components/#labels) for "Win" and "Loss" should help with readability.

As for showing which have been downloaded, that's covered by issue #51

**Comment by michaelwisely** [comment]
This was fixed by upgrading to Bootstrap 3. The colors are more defined.
