### ISSUE TITLE
Contact info

### ISSUE THREAD

**Issue by russleyshaw** [siggame/webserver#71]
There is not a place to get in contact with SIG-Game.

Might want to include somewhere chair email and siggame email

siggame(at)mst.edu
russley.shaw(at)mst.edu

**Comment by michaelwisely** [comment]
We can add this to the "about us" page on [siggame/siggame.github.io](https://github.com/siggame/siggame.github.io).

**Comment by jonsimington** [comment]
see https://github.com/siggame/siggame.github.io/commit/05434d4082ab45d62cd52d2063f904ccd7925f8a
