### ISSUE TITLE
Everygame is completed Zero Minutes ago.

### ISSUE THREAD

**Issue by scj7t4** [siggame/webserver#87]
See:

http://megaminerai.com/competition/megaminerai-13-droids/game/223355/

```
Completed   April 12, 2014, 6:58 p.m. (0 minutes ago) 
```

**Comment by michaelwisely** [comment]
The arena's in UTC, which is ahead of central time. It turns out that the time since a time in the future is zero according to [timesince](https://github.com/siggame/webserver/blob/develop/webserver/templates/competition/game/game_detail.html#L26).
