### ISSUE TITLE
Show gameserver location on the website

### ISSUE THREAD

**Issue by jonsimington** [siggame/webserver#90]
It was hard to communicate when the gameserver changed, and what it changed to.  It'd be useful to display this information on the website.

**Comment by JustinKellogg** [comment]
Is there any sort of site-wide base template?  
Could put a div for the server address and visualizer links in there and have them auto update if/when they change.

**Comment by JustinKellogg** [comment]
Oh, is it
Webserver/template/base.html?

**Comment by jonsimington** [comment]
Yep, that's it.  We will implement this feature before the next megaminer, but it's not at the top of the list right now. 

—

**Comment by michaelwisely** [comment]
Let's see if we can use Stashboard for this.

**Comment by michaelwisely** [comment]
Let's use Stashboard / the blog for this.
